### ISSUE TITLE
Missing tags and releases on pypi

### ISSUE THREAD

**Issue by wagner-certat** [CaliDog/certstream-python#10]
The latest 1.9 release is not on PyPi and no release is tagged in git.

**Comment by Fitblip** [comment]
Hey @wagner-certat - thanks for the heads up. Forgot to push it to pypi! Should be fixed now (https://pypi.python.org/pypi?:action=display&name=certstream&version=1.9)

I'll also add in some release tags. 

Thanks again!
![](https://media1.giphy.com/media/nEMmyUp4hl1QOzovKh/giphy.gif)
