### ISSUE TITLE
module 'certstream' has no attribute 'listen_for_events'

### ISSUE THREAD

**Issue by bedford1234** [CaliDog/certstream-python#15]
Hello,

I'm trying to use CertStream with a proxy, however I get this error message.

Traceback (most recent call last):
  File "certstream.py", line 1, in <module>
    import certstream
  File "/home/.../certstream.py", line 6, in <module>
AttributeError: module 'certstream' has no attribute 'listen_for_events'

Does anyone know a solution to this problem?

**Comment by wagner-certat** [comment]
You have a file called `certstream.py` in your local directory, which masks the actual certstream library. Simply rename the file.

**Comment by bedford1234** [comment]
@wagner-certat Thanks for your help. I was able to fix that error but now I have a different error.

[ERROR:root] 2018-06-22 14:49:11,224 - Error connecting to CertStream - [Errno -2] Name or service not known - Sleeping for a few seconds and trying again...

Any idea of what the problem is?

**Comment by swedishmike** [comment]
@bedford1234 Not sure if you've fixed this second issue yet, but `[Errno -2] Name or service not known` is basically a name resolution problem in most cases. Is name resolution working properly on the host you're testing this on?

**Comment by Fitblip** [comment]
Hey all, I think this is addressed with the recently released downgrade to websocket-client==0.48.0. 

Please let me know if you have further issues!

**Comment by wagner-certat** [comment]
So it is not planned to support websocket-client >= 0.48.0?

**Comment by Fitblip** [comment]
@wagner-certat - not unless there's a compelling reason like a security issue or some other critical bug.
