### ISSUE TITLE
Error connecting to CertStream: SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by hughesdg** [CaliDog/certstream-python#16]
I have the following error:

[ERROR:root] 2018-07-19 18:56:49,459 - Error connecting to CertStream - [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:579) - Sleeping for a few seconds and trying again...

Any ideas?

**Comment by hughesdg** [comment]
Looks to be an issue with my OpenSSL implementation - Works fine on Windows / PyCharm. Will check further....

**Comment by Fitblip** [comment]
Hey there, 

Let me know if there's anything actionable here and I'm happy to take a look!

Thanks,
Ryan
