### ISSUE TITLE
How to write certstream output to json file?

### ISSUE THREAD

**Issue by bedford1234** [CaliDog/certstream-python#17]
Hello,

I see this statement certstream --json | jq -r '.data | [.source.url, (.cert_index|tostring), .leaf_cert.subject.aggregated] | join(",")'  on the certstream.io website, my question is how do I write the certstream results to a json file I can save.

I would greatly appreciate your help!

**Comment by wagner-certat** [comment]
Just use bash features and append `> yourfile.json` to the command

**Comment by bedford1234** [comment]
Hello @wagner-certat 

Thank you for your response! I tried this command and certstream starts listening for events but it produces no output. 

certstream --json | jq -r '.data | [.source.url, (.cert_index|tostring), .leaf_cert.subject.aggregated] | join(",")' > mycertstreamfile.json 

Do you have any clue what is wrong with the command?

**Comment by wagner-certat** [comment]
It produces no output because the output is in the file

**Comment by wagner-certat** [comment]
I do not understand what you want to say.

**Comment by bedford1234** [comment]
@wagner-certat I got the screenshot from the calidog certstream website. If you go to the bottom of the https://certstream.calidog.io/ webpage you will see details there. I want to get all of the attributes like serial number, notbefore, notafter from the certificate in my json file. How would I do that? I would greatly appreciate it!

**Comment by bedford1234** [comment]
@wagner-certat I got the screenshot from the calidog certstream website. If you go to the bottom of the https://certstream.calidog.io/ webpage you will see details there. I want to get all of the attributes like serial number, notbefore, notafter from the certificate in my json file. How would I do that? I would greatly appreciate it!

**Comment by Fusl** [comment]
What you want is just `certstream --json > mycertstreamfile.json`

**Comment by Fitblip** [comment]
@fusl is correct, so I'm going to close this. @bedford1234 - please re-open if there's a bug or some other thing you'd like to discuss.

**Comment by nafeef123** [comment]
Out put jons
