### ISSUE TITLE
Filtering server-side?

### ISSUE THREAD

**Issue by bortzmeyer** [CaliDog/certstream-python#22]
[I'm not sure if I should file this issue here or with CaliDog/certstream-server. But I experience the problem with a Python program, so...]

If you are interested only by a subset of the certificates (for instance based on the domain name), filtering them client-side is a lot of work since the firehose is very active. My Python client takes a lof of CPU for that. And it also requires to download everything.

Is there a way to request a filtering server-side? I cannot find it in the code or the server nor in the documentation.

**Comment by realalexandergeorgiev** [comment]
Then client is the wrong repo for you. Try server. Also I think that using CaliDog's bandwidth is only good for testing, not for production
