### ISSUE TITLE
Experiencing frequent websocket stream reconnects

### ISSUE THREAD

**Issue by lorenzbausch** [CaliDog/certstream-python#27]
Using version 1.10 and the sample code from the readme, roughly every minute a reconnect occurs, preceded by the following message:

```
[ERROR:root] 2019-10-11 16:38:18,582 - Error connecting to CertStream - Connection is already closed. - Sleeping for a few seconds and trying again...
```

**Comment by 0xroot** [comment]
I've experienced the same issue here. At first thought it could be associated with WSS on low ports, but even when running any example as root, still hits the same issue.

**Comment by neonknight** [comment]
same for me, not getting any certstream data, only reconnects.

**Comment by Fitblip** [comment]
Hey folks, sorry for the delay here.

Digging into this, it looks like cowboy (the underlying websocket server for certstream) will timeout connections after a minute and force reconnection - https://github.com/ninenines/cowboy/issues/1259

I didn't realize this and figured another mechanism would be handling heartbeats, which doesn't seem to be the case. I'm going to add heartbeating to this and the other clients which should (hopefully) remedy these timeout issues (the golang client is experiencing this as well - https://github.com/CaliDog/certstream-go/issues/8).

**Comment by Fitblip** [comment]
This is now live with `certstream-python==1.11`! Let me know if you have any issues.

**Comment by neonknight** [comment]
looks good so far, thank you for the fix!

**Comment by 0xroot** [comment]
thanks for the fix, works like charm!

**Comment by t4d** [comment]
Nice! Thank you for the fix.

**Comment by Fitblip** [comment]
Thanks for the info! Cheers, and happy holidays!
