### ISSUE TITLE
Python not producing any domains after CloudFlare outage

### ISSUE THREAD

**Issue by Peter200lx** [CaliDog/certstream-python#33]
If I click `OPEN THE FIRE HOSE` from https://certstream.calidog.io/ I'll see domains streaming in, but if I fresh run `pip install certstream` and run `$ certstream --full` I get no domains.

The issue started happening with the CloudFlare outage. Initially I saw some timeouts/resets around 12:10-12:15 PDT:
```
Certificate stream exception -> [Errno 104] Connection reset by peer
Certificate stream exception -> [Errno 110] Connection timed out
```
And then DNS resolution failures between 12:16-12:25:
```
Certificate stream exception -> [Errno -3] Temporary failure in name resolution
```

But since then I can establish the connection without error, but no messages are being sent over the socket:
```
$ certstream --full
[INFO:certstream] 2020-07-17 16:46:35,371 - Connection established to CertStream! Listening for events...
^C[INFO:certstream] 2020-07-17 16:47:55,299 - Kill command received, exiting!!
```

**Comment by Fitblip** [comment]
Hi there, thanks a ton for the heads up! It seems there’s some issues with the certstream server and it was unable to recover from the outage today. 

I’ve set up a monitor to let me know next time it goes down!

Cheers,
Ryan

**Comment by Peter200lx** [comment]
I can confirm that I'm seeing domains on the CLI again, thanks much!
