### ISSUE TITLE
ERROR:websocket

### ISSUE THREAD

**Issue by Dikko3506** [CaliDog/certstream-python#45]
[ERROR:websocket] 2021-03-30 06:50:03,531 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7f400c29b3d0>>: 'chain'

![image](https://user-images.githubusercontent.com/43563193/112947386-57b9b200-9154-11eb-8c45-974ab676b2c0.png)

i am getting this error using 
websocket-client>=0.58.0 and 
certstream==1.10

how i can solve this ?

**Comment by HugooB** [comment]
Downgrade your `websocket-client` package to 0.57.0 (check https://github.com/CaliDog/certstream-python/issues/42)

**Comment by Dikko3506** [comment]
> Downgrade your `websocket-client` package to 0.57.0 (check #42)

![image](https://user-images.githubusercontent.com/43563193/113017088-bdca2780-919c-11eb-804f-c2aad4e04d75.png)

**Comment by HugooB** [comment]
You might want to try downgrading to `websocket-client` 0.56.0 as mentioned in the [requirements](https://github.com/CaliDog/certstream-python/blob/master/requirements.txt)

**Comment by Dikko3506** [comment]
> You might want to try downgrading to `websocket-client` 0.56.0 as mentioned in the [requirements]

sir after i downgrade to 0.56.0-0.48.0 i got this error " error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7f400c29b3d0>>: 'chain'"

**Comment by Fitblip** [comment]
Hi folks, this should be fixed with #42
