### ISSUE TITLE
Is possible to monitor phishing/fake certificate?

### ISSUE THREAD

**Issue by jmrkvicka909** [CaliDog/certstream-python#47]
Hi, 
I am sorry, I think I didn't understand purpose of this script, so I would like to ask about one thing.
I want to monitor all issued certificate for domain which contains my domain. Let's say, my domain is example.com so I would like to know about new certificates for e.g. xxxexample.com, example.asdfkjgfle.com etc. Is possible for this purpose use this script? Are there any other examples of using this script? Thank you very much for your answers.

**Comment by wagner-certat** [comment]
Have a look at https://github.com/x0rz/phishing_catcher/
