### ISSUE TITLE
Error connecting to CertStream - [Errno -3]

### ISSUE THREAD

**Issue by matterumirai** [CaliDog/certstream-python#49]
Hello,

I use a Python script to get stream. It works properly for 2 hours and get the error following:

`Error connecting to CertStream - [Errno -3] Temporary failure in name resolution - Sleeping for a few seconds and trying again...`

I kill and rerun the script but same error

Do you have any idea?

Thanks in advance.

**Comment by d-Rickyy-b** [comment]
Duplicate of https://github.com/CaliDog/certstream-python/issues/35

**Comment by Fitblip** [comment]
> Temporary failure in name resolution

This seems like a DNS issue on your local network @matterumirai - please re-open if you're still having issues.
