### ISSUE TITLE
Error Connecting to Certstream 

### ISSUE THREAD

**Issue by isa1821** [CaliDog/certstream-python#61]
Since last week, I can't connect to Certstream calidog to get certification info. Does anyone know when this problem is going to be fixed?

**Comment by Fitblip** [comment]
Hi, apologies for the downtime. 

The public server is not really meant to be consumed for more than simple proofs of concepts - if you're ingesting this data yourself you should consider running your own server - https://github.com/CaliDog/certstream-server. There are congestion issues that might cause you to lose certificates when the server's bandwidth is maxed out (which is usually the case despite it being a gigabit connection). 

Things are back up but please consider running your own server if you're using it for something important!
