### ISSUE TITLE
SSL connection issue

### ISSUE THREAD

**Issue by nabeelxy** [CaliDog/certstream-python#9]
I am getting the following error when trying to use certstream - (it used to work without any issues before though) : Error connecting to CertStream - Handshake status 502 

Could you please help me resolve it in my env?

I have Python 2.7.14 running on CentOS 7.4.1708.

Thanks.

**Comment by nabeelxy** [comment]
Unfortunately I am getting the same error with Python 3.6 as well.

**Comment by Fitblip** [comment]
Hi there, 

You're getting a 502 because the service is currently down while I'm in billing dispute with Google. You can find more information at https://certstream.calidog.io

**Comment by Fitblip** [comment]
This should be fixed shortly, I migrated everything back to Heroku for now.

**Comment by nabeelxy** [comment]
Thank you @Fitblip. I use this for a research project I am doing.
